# Generated by Django 5.1.5 on 2025-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletionreport',
            name='worked_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
