# Generated by Django 5.2 on 2025-05-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_deletedtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deletedtask',
            old_name='Org_id',
            new_name='org_id',
        ),
    ]
