# Generated by Django 5.2 on 2025-05-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_rename_org_id_deletedtask_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletionreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completionreports', to='taskapp.task'),
        ),
    ]
